// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHeR_tGj9ao06S9B4oZz6BpFcIdczoZx8',
    appId: '1:768607411257:web:e4173d2857d697f33841e8',
    messagingSenderId: '768607411257',
    projectId: 'flypro-expesne-tracker',
    authDomain: 'flypro-expesne-tracker.firebaseapp.com',
    storageBucket: 'flypro-expesne-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB320SNhdFjqdKFQ2clWIz_rFqlKFUzoKc',
    appId: '1:768607411257:android:9ac0dacf61e890e43841e8',
    messagingSenderId: '768607411257',
    projectId: 'flypro-expesne-tracker',
    storageBucket: 'flypro-expesne-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRcWDfim9npG5Hiq7JFEGyHtPSj9VyBz4',
    appId: '1:768607411257:ios:6b3d6b0c58ced4a43841e8',
    messagingSenderId: '768607411257',
    projectId: 'flypro-expesne-tracker',
    storageBucket: 'flypro-expesne-tracker.firebasestorage.app',
    iosBundleId: 'com.example.flyproExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRcWDfim9npG5Hiq7JFEGyHtPSj9VyBz4',
    appId: '1:768607411257:ios:6b3d6b0c58ced4a43841e8',
    messagingSenderId: '768607411257',
    projectId: 'flypro-expesne-tracker',
    storageBucket: 'flypro-expesne-tracker.firebasestorage.app',
    iosBundleId: 'com.example.flyproExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHeR_tGj9ao06S9B4oZz6BpFcIdczoZx8',
    appId: '1:768607411257:web:adf930652220b6e23841e8',
    messagingSenderId: '768607411257',
    projectId: 'flypro-expesne-tracker',
    authDomain: 'flypro-expesne-tracker.firebaseapp.com',
    storageBucket: 'flypro-expesne-tracker.firebasestorage.app',
  );
}
